#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := quest3

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/$(PROJECT_NAME)/protocol_examples_common

include $(IDF_PATH)/make/project.mk
